// AttorneyDetails.jsx
const AttorneyDetails = [
  {
    AttorneyID: 1,
    AttorneyName: "Rajesh Kumar",
    Email: "rajesh.kumar@legalfirm.in",
    PhoneNumber: "+91 9876543210",
    LawFirm: "Kumar & Associates",
    Specialization: "Intellectual Property Law",
    AssignedApplicationID: 101,
    AssignmentDate: "2024-06-01",
    Status: "Reviewed",
    FeedbackReceived: "Yes",
    Comments: "Reviewed the patent documents and suggested minor changes.",
    AttorneyFee: "₹25,000",
    ReviewStatus: "Completed",
    LastUpdated: "2024-06-05",
    CreatedBy: "Admin",
  },
  {
    AttorneyID: 2,
    AttorneyName: "Sita Devi",
    Email: "sita.devi@patentlawyers.com",
    PhoneNumber: "+91 8123456789",
    LawFirm: "Patent Lawyers LLP",
    Specialization: "Patent Filing & Litigation",
    AssignedApplicationID: 102,
    AssignmentDate: "2024-07-10",
    Status: "Pending",
    FeedbackReceived: "No",
    Comments: "Awaiting initial review.",
    AttorneyFee: "₹30,000",
    ReviewStatus: "Pending",
    LastUpdated: "2024-07-12",
    CreatedBy: "Director",
  },
  {
    AttorneyID: 3,
    AttorneyName: "Anand Verma",
    Email: "anand.verma@ipjuris.com",
    PhoneNumber: "+91 7987654321",
    LawFirm: "IP Juris",
    Specialization: "Patent Drafting & Consultation",
    AssignedApplicationID: 103,
    AssignmentDate: "2024-08-15",
    Status: "In Progress",
    FeedbackReceived: "No",
    Comments: "Drafting the initial patent application.",
    AttorneyFee: "₹20,000",
    ReviewStatus: "In Progress",
    LastUpdated: "2024-08-16",
    CreatedBy: "Admin",
  },
  // Add more attorney details here if needed
];

export default AttorneyDetails;
