const AttorneyDetails = [
  {
    AttorneyID: 1,
    AttorneyName: "Rajesh Kumar",
    Email: "rajesh.kumar@legalfirm.in",
    PhoneNumber: "+91 9876543210",
    LawFirm: "Kumar & Associates",
    Specialization: "Intellectual Property Law",
    AssignedApplicationID: 101,
    AssignmentDate: "2024-06-01",
    Status: "Reviewed",
    FeedbackReceived: "Yes",
    Comments: "Reviewed the patent documents and suggested minor changes.",
    AttorneyFee: "₹25,000",
    ReviewStatus: "Completed",
    LastUpdated: "2024-06-05",
    CreatedBy: "Admin",
  },
  {
    AttorneyID: 2,
    AttorneyName: "Sita Devi",
    Email: "sita.devi@patentlawyers.com",
    PhoneNumber: "+91 8123456789",
    LawFirm: "Patent Lawyers LLP",
    Specialization: "Patent Filing & Litigation",
    AssignedApplicationID: 102,
    AssignmentDate: "2024-07-10",
    Status: "Pending",
    FeedbackReceived: "No",
    Comments: "Awaiting initial review.",
    AttorneyFee: "₹30,000",
    ReviewStatus: "Pending",
    LastUpdated: "2024-07-12",
    CreatedBy: "Director",
  },
  {
    AttorneyID: 3,
    AttorneyName: "Anand Verma",
    Email: "anand.verma@ipjuris.com",
    PhoneNumber: "+91 7987654321",
    LawFirm: "IP Juris",
    Specialization: "Patent Drafting & Consultation",
    AssignedApplicationID: 103,
    AssignmentDate: "2024-08-15",
    Status: "In Progress",
    FeedbackReceived: "No",
    Comments: "Drafting the initial patent application.",
    AttorneyFee: "₹20,000",
    ReviewStatus: "In Progress",
    LastUpdated: "2024-08-16",
    CreatedBy: "Admin",
  },
  {
    AttorneyID: 4,
    AttorneyName: "Neha Sharma",
    Email: "neha.sharma@innovlaw.com",
    PhoneNumber: "+91 9123456789",
    LawFirm: "InnovLaw Partners",
    Specialization: "Technology Law",
    AssignedApplicationID: 104,
    AssignmentDate: "2024-09-01",
    Status: "Reviewed",
    FeedbackReceived: "Yes",
    Comments: "Provided extensive review comments.",
    AttorneyFee: "₹28,000",
    ReviewStatus: "Completed",
    LastUpdated: "2024-09-03",
    CreatedBy: "Director",
  },
  {
    AttorneyID: 5,
    AttorneyName: "Vikram Singh",
    Email: "vikram.singh@lawbridge.com",
    PhoneNumber: "+91 9988776655",
    LawFirm: "LawBridge Associates",
    Specialization: "International IP Law",
    AssignedApplicationID: 105,
    AssignmentDate: "2024-09-10",
    Status: "In Progress",
    FeedbackReceived: "No",
    Comments: "Currently assessing patentability.",
    AttorneyFee: "₹35,000",
    ReviewStatus: "In Progress",
    LastUpdated: "2024-09-15",
    CreatedBy: "Admin",
  },
  {
    AttorneyID: 6,
    AttorneyName: "Priya Joshi",
    Email: "priya.joshi@iprsolutions.com",
    PhoneNumber: "+91 9090909090",
    LawFirm: "IPR Solutions",
    Specialization: "Patent Litigation",
    AssignedApplicationID: 106,
    AssignmentDate: "2024-10-01",
    Status: "Pending",
    FeedbackReceived: "No",
    Comments: "Awaiting client feedback.",
    AttorneyFee: "₹40,000",
    ReviewStatus: "Pending",
    LastUpdated: "2024-10-05",
    CreatedBy: "Admin",
  },
  {
    AttorneyID: 7,
    AttorneyName: "Arjun Mehta",
    Email: "arjun.mehta@legaladvocates.com",
    PhoneNumber: "+91 8765432100",
    LawFirm: "Legal Advocates",
    Specialization: "Corporate & IP Law",
    AssignedApplicationID: 107,
    AssignmentDate: "2024-10-15",
    Status: "Reviewed",
    FeedbackReceived: "Yes",
    Comments: "Approved patent application with no changes.",
    AttorneyFee: "₹27,000",
    ReviewStatus: "Completed",
    LastUpdated: "2024-10-20",
    CreatedBy: "Director",
  },
  {
    AttorneyID: 8,
    AttorneyName: "Divya Kapoor",
    Email: "divya.kapoor@kapoorlaw.com",
    PhoneNumber: "+91 9988123456",
    LawFirm: "Kapoor Law Offices",
    Specialization: "Intellectual Property & Copyright",
    AssignedApplicationID: 108,
    AssignmentDate: "2024-11-01",
    Status: "In Progress",
    FeedbackReceived: "No",
    Comments: "Preparing for initial client discussion.",
    AttorneyFee: "₹32,000",
    ReviewStatus: "In Progress",
    LastUpdated: "2024-11-03",
    CreatedBy: "Admin",
  }
];

export default AttorneyDetails;
