export const NewApplicationData = [
  {
    "Token Number": "IIITDMJ/AGR/20241107/001/AAS/104",
    "Patent Title": "Smart Irrigation System",
    "Submitted By": "Aarav Sharma",
    Designation: "Research Scientist",
    Department: "Agricultural Sciences",
    "Date - Time": "2024-11-07 10:00 AM",
  },
  {
    "Token Number": "IIITDMJ/SM/20241107/002/NVV/105",
    "Patent Title": "Eco-Friendly Packaging Material",
    "Submitted By": "Neha Verma",
    Designation: "Product Designer",
    Department: "Sustainable Materials",
    "Date - Time": "2024-11-07 11:30 AM",
  },
  {
    "Token Number": "IIITDMJ/HT/20241107/003/RSR/106",
    "Patent Title": "AI-Powered Medical Diagnosis",
    "Submitted By": "Rohan Singh",
    Designation: "Data Scientist",
    Department: "Healthcare Technology",
    "Date - Time": "2024-11-07 12:45 PM",
  },
  {
    "Token Number": "IIITDMJ/RE/20241107/004/PPT/107",
    "Patent Title": "Solar Energy Optimizer",
    "Submitted By": "Priya Patel",
    Designation: "Energy Analyst",
    Department: "Renewable Energy",
    "Date - Time": "2024-11-07 01:15 PM",
  },
  {
    "Token Number": "IIITDMJ/SE/20241107/005/KMR/108",
    "Patent Title": "Blockchain-Based Voting System",
    "Submitted By": "Karan Mehta",
    Designation: "Blockchain Developer",
    Department: "Software Engineering",
    "Date - Time": "2024-11-07 02:00 PM",
  },
];

export const ReviewedApplicationsData = [
  {
    title: "Machine Learning Model for Predicting Crop Yield",
    date: "2024-10-15",
    time: "10:30 AM",
    tokenNumber: "R-001",
    applicationNumber: "APP-2457",
    attorney: "Aditi Shah",
    borderColor: "#28a745",
  },
  {
    title: "Eco-Friendly Textile Dyeing Process",
    date: "2024-10-20",
    time: "2:00 PM",
    tokenNumber: "R-002",
    applicationNumber: "APP-2481",
    attorney: "Rajesh Kumar",
    borderColor: "#ff6347",
  },
  {
    title: "Smart Waste Management System",
    date: "2024-11-01",
    time: "9:00 AM",
    tokenNumber: "R-003",
    applicationNumber: "APP-2553",
    attorney: "Sakshi Jain",
    borderColor: "#1e90ff",
  },
  {
    title: "AI-Based Cancer Detection Tool",
    date: "2024-11-03",
    time: "11:45 AM",
    tokenNumber: "R-004",
    applicationNumber: "APP-2601",
    attorney: "Anil Tiwari",
    borderColor: "#daa520",
  },
  {
    title: "Low-Cost Water Filtration System",
    date: "2024-11-05",
    time: "4:00 PM",
    tokenNumber: "R-005",
    applicationNumber: "APP-2650",
    attorney: "Nisha Agarwal",
    borderColor: "#ff4500",
  },
  {
    title: "Automated Smart Home Security System",
    date: "2024-11-06",
    time: "5:30 PM",
    tokenNumber: "R-006",
    applicationNumber: "APP-2675",
    attorney: "Mohan Singh",
    borderColor: "#32cd32",
  },
];
