// StatusOfApplicationData.js

export const StatusOfApplicationData = [
  {
    "Token Number": "IIITDMJ/AGR/20241107/001/AAS/104",
    "Patent Title": "Smart Irrigation System",
    "Submitted By": "Aarav Sharma",
    Designation: "Research Scientist",
    Department: "Agricultural Sciences",
    "Date - Time": "2024-11-07 10:00 AM",
    Status: "Under Review",
  },
  {
    "Token Number": "IIITDMJ/SM/20241107/002/NVV/105",
    "Patent Title": "Eco-Friendly Packaging Material",
    "Submitted By": "Neha Verma",
    Designation: "Product Designer",
    Department: "Sustainable Materials",
    "Date - Time": "2024-11-07 11:30 AM",
    Status: "Pending",
  },
  {
    "Token Number": "IIITDMJ/HT/20241107/003/RSR/106",
    "Patent Title": "AI-Powered Medical Diagnosis",
    "Submitted By": "Rohan Singh",
    Designation: "Data Scientist",
    Department: "Healthcare Technology",
    "Date - Time": "2024-11-07 12:45 PM",
    Status: "Approved",
  },
  {
    "Token Number": "IIITDMJ/RE/20241107/004/PPT/107",
    "Patent Title": "Solar Energy Optimizer",
    "Submitted By": "Priya Patel",
    Designation: "Energy Analyst",
    Department: "Renewable Energy",
    "Date - Time": "2024-11-07 01:15 PM",
    Status: "In Progress",
  },
  {
    "Token Number": "IIITDMJ/SE/20241107/005/KMR/108",
    "Patent Title": "Blockchain-Based Voting System",
    "Submitted By": "Karan Mehta",
    Designation: "Blockchain Developer",
    Department: "Software Engineering",
    "Date - Time": "2024-11-07 02:00 PM",
    Status: "Rejected",
  },
  {
    "Token Number": "IIITDMJ/CS/20241108/006/RTY/109",
    "Patent Title": "Quantum Computing Algorithm for Cryptography",
    "Submitted By": "Riya Thakur",
    Designation: "Quantum Researcher",
    Department: "Computer Science",
    "Date - Time": "2024-11-08 09:30 AM",
    Status: "Under Review",
  },
  {
    "Token Number": "IIITDMJ/ME/20241108/007/AJL/110",
    "Patent Title": "Self-Healing Materials for Robotics",
    "Submitted By": "Ajay Lal",
    Designation: "Mechanical Engineer",
    Department: "Mechanical Engineering",
    "Date - Time": "2024-11-08 11:00 AM",
    Status: "Approved",
  },
  {
    "Token Number": "IIITDMJ/CE/20241108/008/SSK/111",
    "Patent Title": "AI-Assisted Construction Planning",
    "Submitted By": "Sneha Kapoor",
    Designation: "Civil Engineer",
    Department: "Civil Engineering",
    "Date - Time": "2024-11-08 02:15 PM",
    Status: "Pending",
  },
];
